### ISSUE TITLE
Dev versions should be valid PEP 440 versions

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#151]
Today they have hyphens between parts. My read of 440 is they should have only periods.

**Comment by riastradh-probcomp** [comment]
Fixed in edb408bcf26b1e3c2562602ebad080a6b33aa9a6, 7400edd31dfe1217039b54e725d1cff70c3db2db.  New scheme is, e.g.,

    1.3a20151008.32+g829b37a-dirty

- `1.3` is the main version number;
- `a` marks as alpha, i.e. development version;
- `20151008` is the most recent development snapshot date;
- `32` is the number of commits since the snapshot;
- `829b37a` is (a prefix of) the Git commit id;
- `-dirty` means the working tree was dirty.

We use `a` now because `dev` sorts lexicographically after `b`, and because PEP 440 and Debian disagree on its interpretation.
