### ISSUE TITLE
Convert correlation code to use numpy arrays

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#213]
Should provide significant speedup -- no reason trivial operation like correlations should be performance bottleneck.

**Comment by axch** [comment]
The next step on this task is to get a command line that produces a profile dominated by the slowness of correlation (and, e.g., post the command and the profile here).  That will indicate whether a numpy rewrite is, in fact, the thing to do.

**Comment by riastradh-probcomp** [comment]
Date: Wed, 30 Sep 2015 10:40:42 -0700
   From: axch <notifications@github.com>

   The next step on this task is to get a command line that produces a
   profile dominated by the slowness of correlation (and, e.g., post
   the command and the profile here).  That will indicate whether a
   numpy rewrite is, in fact, the thing to do.

Not necessary.  It's pretty self-evident.  I avoided numpy at the time
because at about that time you and I were talking about making a
numpy-free version of Venture, and I saw that numpy took forever to
build and was otherwise not relevant to bayeslite.

**Comment by riastradh-probcomp** [comment]
Draft on branch 20151008-riastradh-correlnumpy.  Please review!

**Comment by raxraxraxraxrax** [comment]
@riastradh-probcomp It looks like this was merged in; can you please confirm? Thanks!

**Comment by riastradh-probcomp** [comment]
Merged in f89851ca5f1534923768ce1f24cc380435c3a03d.

**Comment by riastradh-probcomp** [comment]
There was some lingering question about whether to continue using `float_sum` or to use `numpy.sum`.  I forget how it was resolved, but I don't really care for this purpose.
