### ISSUE TITLE
Implement conditional mutual information in metamodel instead of column mutual information

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#279]
See the implementation of function by the same name in [`foreign/composer.py`](https://github.com/probcomp/bdbcontrib/blob/fsaad-foreign-predictor/src/metamodels/composer.py#L458).

**Comment by axch** [comment]
If implemented, would subsume #269 as a special case (though perhaps an optimizable one).

**Comment by gregory-marton** [comment]
@fsaad, I get a 404 for that link now. @axch too, can you give more context? Where would you recommend reading about the math, and why is the change desirable?

**Comment by riastradh-probcomp** [comment]
Please give links to specific commits!  Here's likely what @fsaad was citing: https://github.com/probcomp/bdbcontrib/blob/ba8d10e9aa741a05d7f86c66548805f1b74c2773/src/metamodels/composer.py  (Stupid Git doesn't know any association between branches and commits other than whatever is the current commit a branch is at.  And since someone deleted the branch, the issue can no longer even refer to that.)

**Comment by axch** [comment]
Don't know whether "instead" is the right thing, but "in addition" certainly seems desirable, at least on general principle.  Math writeup now lives in https://github.com/probcomp/bdb-experiments/commit/de246884daf3043486805c28a5ed05dacf2ecb18#diff-aeb232468aa592f22b8141343fda8001R720

**Comment by fsaad** [comment]
244af1972043b9034d2f5dbc4c83ee199802baff
