### ISSUE TITLE
Option: Could define constrained logpdf as the difference of two unconstrained logpdfs

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#290]
Benefit: slight (optional) simplification of the metamodel implementor's job.

**Comment by riastradh-probcomp** [comment]
Downside: prevents the metamodel from avoiding catastrophic cancellation by evaluating a difference of logpdfs cleverly.

**Comment by axch** [comment]
We could leave the constrained version in the interface as an option.

**Comment by fsaad** [comment]
As of bayeslite-v2 the implementation of logpdf delegates to the `cgpm` responsible for those subset of variables; how these cgpms implement unconstrained cgpms is an internal modeling choice (for example, multivariate KDE cgpm implements the constrained logpdf as a difference of two unconstrained logpdfs, while a CrossCat view using the latent cluster assignment to prevent unnecessary joint/marginal computations). I don't think these choices should be made by the BQL interpreter, since it might be going in circles undoing the internal choice by the cgpm. @leocasarsa
