### ISSUE TITLE
test suite does not cover SIMILARITY WITH RESPECT TO (*)

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#348]
https://github.com/probcomp/bayeslite/blob/fb6699209d7cec886b4f15fa6d81f73b7d858d24/src/compiler.py#L1112-L1113

**Comment by fsaad** [comment]
Tested in the parser as:
https://github.com/probcomp/bayeslite/blob/4548e767491491f4b2a42f48b30b1d3cebf5c08c/tests/test_parse.py#L343-L345

This query is no longer supported in the compiler, since WITH RESEPCT TO (now IN THE CONTEXT OF) accepts only one column, with the error being captured in this test:

https://github.com/probcomp/bayeslite/blob/4548e767491491f4b2a42f48b30b1d3cebf5c08c/tests/test_bql.py#L565-L568
