### ISSUE TITLE
BusyError: database is locked when opening bdb

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#378]
I opened a bdb (which was performing analysis) in another shell, and received the following error (in the shell running analysis)

```
   1031                 if ckpt_iterations is not None:
-> 1032                     ckpt_counter = ckpt_iterations
   1033
   1034     def column_dependence_probability(self, bdb, generator_id, modelno,

/usr/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     22         if type is None:
     23             try:
---> 24                 self.gen.next()
     25             except StopIteration:
     26                 return

/scratch/fs/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py in savepoint(self)
    294         """
    295         with txn.bayesdb_savepoint(self):
--> 296             yield
    297
    298     @contextlib.contextmanager

/usr/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     22         if type is None:
     23             try:
---> 24                 self.gen.next()
     25             except StopIteration:
     26                 return

/scratch/fs/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/txn.py in bayesdb_savepoint(bdb)
     38     try:
     39         with sqlite3_savepoint(bdb._sqlite3):
---> 40             yield
     41     finally:
     42         bayesdb_txn_pop(bdb)

/usr/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     22         if type is None:
     23             try:
---> 24                 self.gen.next()
     25             except StopIteration:
     26                 return

/scratch/fs/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/sqlite3_util.py in sqlite3_savepoint(db)
     69         if not ok:
     70             db.cursor().execute("ROLLBACK TO x%s" % (savepoint,))
---> 71         db.cursor().execute("RELEASE x%s" % (savepoint,))
     72
     73 @contextlib.contextmanager

src/cursor.c in resetcursor()

BusyError: BusyError: database is locked
```

I don't have the full stack trace (screen ate it), but can provide answers to more detailed questions.

**Comment by fsaad** [comment]
Opening the bdb in two shells may have been a red herring since I just received exactly the same error with the bdb open in one shell...

**Comment by gregory-marton** [comment]
Unsure what you mean by "one shell" vs. two. In one shell, how were you going about connecting to the db while it was analyzing?

I would expect any other connection during analysis to result in a busy db. Other operations make a db busy too. I once experienced a pretty durable busy like this after a drop table. I had to do bdb.reconnect() before it would let me work again, even though the drop table had completed and checkpointed.

**Comment by riastradh-probcomp** [comment]
There are two different kinds of 'locked' errors.

SQLITE3_BUSY means another process (or another database connection, at least) currently holds the database lock, preventing new processes from writing to it (and possibly from reading from it).

SQLITE3_LOCKED means you tried to do something to a table that would break a cursor that is still open for the table.  For example, if you do this:

    cursor = bdb.execute('select * from t')
    bdb.execute('drop table t')

then you will get SQLITE3_LOCKED (unless perhaps it happens to be the case that t is empty).

In this issue, the error almost certainly arises because the second shell you opened did a short transaction that would block the shell doing analysis.  We have not hooked up any logic to enable sqlite3 to block -- if an operation would require waiting for a lock, it raises an error instead.  We could do that with apsw pretty easily, but we need to decide what the right semantics is: do we block forever? for a short period of time? as long as the user requests? differently in API, shell, quickstart? &c.

**Comment by riastradh-probcomp** [comment]
Another option is to run analysis within a transaction or savepoint -- then attempts to read the database from another process will be blocked until the analysis is complete, but conversely they won't be able to block analysis from writing a checkpoint periodically.

**Comment by fsaad** [comment]
If I recall correctly, this issue was related to expiring AFS tokens.
