### ISSUE TITLE
Satellites notebook: bar graph fails silently

### ISSUE THREAD

**Issue by Munklar** [probcomp/bayeslite#379]
One of the steps (step 8) in the Satellites demo is to display a bar graph of simulated satellite data. It depends on a temporary table (satellite_purpose) having been created previously (step 7) and will squawk if the table doesn’t exist. 

It also depends on the matplotlib library having been loaded previously (step 6). If the library has not been loaded, then step 8 returns with no output (i.e., no bar graph) and no error conditions. The terminal console for the python kernel shows no warnings or diagnostics (although even if it did I think many first time users would not think to check there). 

On my Mac, the Python icon in my application dock appears and jumps up and down to indicate it wants attention but clicking on it does nothing.

It is useful to do quick cut/paste work on the Satellites notebook to review or demonstrate portions of it - that’s what I was doing - and it would have been helpful if an error message of some kind came up to explain that it couldn’t find the graphing library I was invoking.

**Comment by gregory-marton** [comment]
So in fact, it found matplotlib just fine, just didn't display it inline so you could see it. The figure would have been there, and if you had done a matplotlib.pyplot.show() you would even have seen it. Because this distinction is in the Jupyter notebook and not in our code, it's sort of hard for us to even detect.

And there are other perfectly reasonable things to do besides %matplotlib inline, so we can't in the library legislate that exactly that should be available.

Which is to say, I wish we could help you, but no trivial solution presents itself, and this is outside the core of what we'd like to work on.
