### ISSUE TITLE
Can bayesdb benefit from using faster sql engine like ClickHouse ?

### ISSUE THREAD

**Issue by kk00ss** [probcomp/bayeslite#422]
My guess is that sqlite is not the fastest engine available. Where is an integration layer lockated in sources, how hard could it be to try other DBMSs ?
ClickHouse is quite mature technology, only recently opensourced by Yandex.
https://github.com/yandex/ClickHouse

**Comment by vkmvkmvkmvkm** [comment]
Are you interested in helping out with the project? Ultimately we will want
embeddings of BQL and MML in other database environments --- though I think
Spark is the most important target after sqlite.

**Comment by kk00ss** [comment]
If there are clearly defined interfaces for DBMS integration - than I'm curious.
Still have to try Spark. Are there any milestones, and plans for the project, like Jira ? or whatever ?

**Comment by vkmvkmvkmvkm** [comment]
In a couple weeks, we'll be releasing a version that makes some of the most
important interfaces explicit. Please let us know if you'd like to consider
putting together a prototype Spark embedding.

**Comment by riastradh-probcomp** [comment]
The only bottleneck in bayeslite related to the SQL engine is the serial evaluation of otherwise independent functions in large queries that are embarrassingly parallelizable, e.g. computing the dependence probability between every pair of variables in

    ESTIMATE DEPENDENCE PROBABILITY FROM PAIRWISE COLUMNS OF t

Actually retrieving data from the tables being analyzed and processing functions of those data is not a bottleneck.

See <https://github.com/probcomp/bayeslite/issues/257#issuecomment-148777952> for some further discussion of this and <https://github.com/probcomp/bdbcontrib/blob/master/src/parallel.py> for an attempt to work around this limitation of sqlite3.

**Comment by kk00ss** [comment]
Do you mean  that IO and filtering are not a problem at all ? I need to better understand internals before making any proposals, my bad. I need to make myself more familiar with both technologies, but yes I am interested in this kind of work.

**Comment by kk00ss** [comment]
Are there any docs on architecture ?

**Comment by kk00ss** [comment]
Found http://probcomp.csail.mit.edu/bayesdb/doc/
