### ISSUE TITLE
switch CGPM tests to use real satellite data set

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#448]
The nonsense data generator I wrote was expedient but silly.

**Comment by fsaad** [comment]
I disagree with this issue. The real satellite data set is a beast suitable for "battle conditions" or some large integration test for missing data, werid strings/unicode characters, large categoricals and so on. 

The stubbed data generator you wrote was perfect for me as a test case and I think it should stay because it is easy to debug.

**Comment by riastradh-probcomp** [comment]
OK.
