### ISSUE TITLE
Unified BQL syntax for row/column operations

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#66]
The BQL language has a semantic inconsistency when specifying row/column operations

operates on rows: `ESTIMATE <columns> FROM <generator> ...`
operates on rows: `ESTIMATE PAIRWISE ROW <expression> ...`
operates on columns: `ESTIMATE COLUMNS <columns> ...` 
operates on columns: `ESTIMATE PAIRWISE <columns> ...`

The suggestion is to unify the BQL syntax in the following way
`ESTIMATE [ PAIRWISE ] <targets> FROM [<generator> | COLUMNS OF <generator>] [ORDER BY ...]`

**Comment by marcoct** [comment]
Out of curiosity, did you consider making "ROWS" explicit?
```
ESTIMATE ... FROM ROWS OF t
ESTIMATE *, ... FROM COLUMNS OF t
ESTIMATE ... FROM PAIRWISE ROWS OF t
ESTIMATE ... FROM PAIRWISE COLUMNS OF t
```

**Comment by riastradh-probcomp** [comment]
No.  In retrospect, perhaps the syntax `COLUMNS OF t` was misleading, and should have been `VARIABLES OF t` or something.  The reason is that columns and rows are not symmetric here -- `ESTIMATE ... FROM (ROWS OF) t` is not simply any sort of transpose of `ESTIMATE ... FROM COLUMNS OF t`.  If it were, the 'variables' in the `...` for `ESTIMATE ... FROM COLUMNS OF t` would be rowids, but who wants to say `ESTIMATE row134, row482, row8 FROM COLUMNS OF t`?

Rather, a table, or more aptly a relation, is always a collection of tuples, and `SELECT ... FROM t` or `ESTIMATE ... FROM t` selects a subset of those tuples.  The concept that `COLUMNS OF t` is meant to evoke -- and that may be better evoked by `VARIABLES OF t` -- is not transposition of data, but rather a table of information about the variables we're modelling, including all their dependence probabilities, their individual marginal distributions, &c.

**Comment by marcoct** [comment]
Thanks. I understand that this is not a matrix we are transposing or sub-selecting, and that `ESTIMATE ... FROM t` is going to return a collection where the fields are properties of the rows, including model estimators of the rows. 

The default interpretation of the generator is identical to the interpretation of the original data table, and `FROM COLUMNS OF` produces a separate object with a different interpretation. Expanding on your suggestion, to make the interpretation of the generator slightly more explicit, and less tied to the original data table interpretation, one could do:
```
ESTIMATE ... FROM OBSERVATIONS OF t
ESTIMATE ... FROM VARIABLES OF t
```
